#!/usr/bin/env bash
# run-android-coffee-test.sh — Full-stack Android test for coffee shop receipt.
#
# Pushes the Playwright screenshot of the Daily Grind receipt to the emulator,
# where ML Kit Text Recognition OCRs it — exercising the full
# camera→OCR→normalize→hash→verify pipeline against a containerized backend.
#
# Authority chain:
#   r.the-daily-grind.co.uk → hmrc.gov.uk/vat → gov.uk/v1
#
# DNS resolution and TLS trust are handled in-app via intent extras:
#   - DNS_OVERRIDES: maps test domains to 10.0.2.2 (emulator host loopback)
#   - trustAllCerts: accepts Caddy's self-signed TLS (debug builds only)
#
# Prerequisites:
#   - Container runtime (docker or podman) with compose
#   - Android SDK with emulator + adb
#   - An existing AVD (set AVD_NAME or defaults to first available)
#   - Rootless port 443: sysctl net.ipv4.ip_unprivileged_port_start=80
#   - jq, curl, sha256sum
#   - public/test-results/coffee-shop-before.png (run the Chrome test first)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
FST_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PROJECT_DIR="$(cd "$FST_DIR/.." && pwd)"
ANDROID_DIR="${PROJECT_DIR}/apps/android"
RESULTS_DIR="${PROJECT_DIR}/public/test-results"
META_DIR="${FST_DIR}/meta"

ANDROID_HOME="${ANDROID_HOME:-$HOME/Android/Sdk}"
ADB_BIN="${ANDROID_HOME}/platform-tools/adb"
ADB="$ADB_BIN -s emulator-5554"
EMULATOR="${ANDROID_HOME}/emulator/emulator"

# Use first available AVD if not specified
AVD_NAME="${AVD_NAME:-$($EMULATOR -list-avds | head -1)}"
if [ -z "$AVD_NAME" ]; then
    echo "Error: no AVD found. Create one with avdmanager or Android Studio."
    exit 1
fi
echo "Using AVD: $AVD_NAME"

# Check that the cropped receipt image exists (generated by the Chrome extension test).
# This is an element screenshot of just the .photo-frame — the receipt on a white
# surface, without the grey page background. Simulates a phone camera pointed at a receipt.
RECEIPT_IMAGE="${RESULTS_DIR}/coffee-shop-receipt-cropped.png"
if [ ! -f "$RECEIPT_IMAGE" ]; then
    echo "Error: $RECEIPT_IMAGE not found."
    echo "Run the Chrome extension coffee test first to generate it."
    exit 1
fi

# Auto-detect compose command
if command -v docker &>/dev/null && docker compose version &>/dev/null 2>&1; then
    COMPOSE="docker compose"
elif command -v podman-compose &>/dev/null; then
    COMPOSE="podman-compose"
else
    echo "Error: no compose tool found (docker compose / podman-compose)"
    exit 1
fi

COMPOSE_FILE="${FST_DIR}/docker-compose.yml"
EMULATOR_PID=""

function cleanup {
    echo "=== Cleaning up ==="
    if [ -n "$EMULATOR_PID" ] && kill -0 "$EMULATOR_PID" 2>/dev/null; then
        echo "Stopping emulator..."
        $ADB -s emulator-5554 emu kill 2>/dev/null || true
        wait "$EMULATOR_PID" 2>/dev/null || true
    fi
    echo "Stopping containers..."
    $COMPOSE -f "$COMPOSE_FILE" down -v 2>/dev/null || true
}
trap cleanup EXIT

# ── 1. Start backend ──────────────────────────────────────────────

# Tear down any stale containers from a previous run
$COMPOSE -f "$COMPOSE_FILE" down -v 2>/dev/null || true

echo "=== Starting backend + Caddy ==="
$COMPOSE -f "$COMPOSE_FILE" up --build -d

echo "=== Waiting for Caddy ==="
for i in $(seq 1 30); do
    if curl -sk --resolve r.the-daily-grind.co.uk:443:127.0.0.1 \
        https://r.the-daily-grind.co.uk/verification-meta.json > /dev/null 2>&1; then
        echo "Caddy ready."
        break
    fi
    if [ "$i" -eq 30 ]; then
        echo "Timeout waiting for Caddy"
        $COMPOSE -f "$COMPOSE_FILE" logs
        exit 1
    fi
    sleep 1
done

# Wait for tier2 write port
echo "=== Waiting for tier2 write port ==="
for i in $(seq 1 30); do
    if curl -s http://localhost:8081/healthz > /dev/null 2>&1; then
        echo "tier2 ready."
        break
    fi
    if [ "$i" -eq 30 ]; then echo "Timeout waiting for tier2"; exit 1; fi
    sleep 1
done

# Helper: compute canonical JSON hash for a meta file
meta_hash() {
    jq -c . < "$1" | tr -d '\n' | sha256sum | cut -d' ' -f1
}

# Helper: seed a hash with a payload
seed() {
    local hash="$1" payload="$2" desc="$3"
    code=$(curl -s -o /dev/null -w '%{http_code}' -X PUT "http://127.0.0.1:8081/v/${hash}" -d "$payload")
    echo "  ${desc}: ${hash:0:16}... -> HTTP ${code}"
}

echo ""
echo "=== Seeding authority chain ==="

DG_META_HASH=$(meta_hash "${META_DIR}/r.the-daily-grind.co.uk/verification-meta.json")
seed "$DG_META_HASH" '{"status":"verified"}' "Daily Grind meta (authorized by hmrc.gov.uk)"

HMRC_META_HASH=$(meta_hash "${META_DIR}/hmrc.gov.uk/vat/verification-meta.json")
seed "$HMRC_META_HASH" '{"status":"verified"}' "HMRC VAT meta (authorized by gov.uk)"

GOV_META_HASH=$(meta_hash "${META_DIR}/gov.uk/v1/verification-meta.json")
seed "$GOV_META_HASH" '{"status":"verified"}' "Gov.uk meta (root authority)"

echo ""
echo "=== Seeding claim hash ==="

CLAIM_HASH=$(node -e "
const { normalizeText } = require('./public/normalize.js');
const crypto = require('crypto');
const text = '8 Market Square\nHenley-on-Thames RG9 2AA\nReceipt: DG-20260315-0017\nDate: 15/03/2026 08:23\nFlat White                  £3.40\nAlmond Croissant            £3.25\nSUBTOTAL:                   £6.65\nVAT @ 20%:                  £1.11\nTOTAL:                      £6.65\nVisa contactless ****3094\nAuth: 718204';
const normalized = normalizeText(text);
const hash = crypto.createHash('sha256').update(normalized).digest('hex');
process.stdout.write(hash);
")
seed "$CLAIM_HASH" '{"status":"verified","message":"Send to Expensify?"}' "Daily Grind receipt"

# ── 2. Build debug APK (while emulator boots) ────────────────────

echo "=== Building debug APK ==="
cd "$ANDROID_DIR"
./gradlew :app:assembleDebug --no-daemon -q
cd "$PROJECT_DIR"

# ── 3. Start emulator ────────────────────────────────────────────

echo "=== Starting emulator ==="
$EMULATOR -avd "$AVD_NAME" \
    -no-snapshot \
    -no-audio \
    -gpu swiftshader_indirect \
    -no-boot-anim \
    &
EMULATOR_PID=$!

echo "Waiting for emulator to boot..."
$ADB wait-for-device
for i in $(seq 1 120); do
    BOOT=$($ADB shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
    if [ "$BOOT" = "1" ]; then
        echo "Emulator booted."
        break
    fi
    if [ "$i" -eq 120 ]; then
        echo "Timeout waiting for emulator boot"
        exit 1
    fi
    sleep 1
done

# Short pause for system services to stabilize
sleep 3

# Suppress ANR dialogs — swiftshader GPU makes everything slow on emulators
echo "=== Suppressing ANR dialogs ==="
$ADB shell settings put secure anr_show_background 0
$ADB shell settings put global activity_manager_constants anr_dialog_enabled=false
$ADB shell setprop dalvik.vm.dex2oat-threads 1

# ── 4. Install APK ───────────────────────────────────────────────

echo "=== Installing APK ==="
$ADB install -r "${ANDROID_DIR}/app/build/outputs/apk/debug/app-debug.apk"

# ── 5. Launch with receipt image + DNS overrides ──────────────────

# Trim most of the white photo-frame border — simulate a human zooming in.
# Keeps a thin margin (5%) so the receipt isn't edge-to-edge.
echo "=== Zooming into receipt (trimming white border) ==="
ZOOMED_IMAGE="/tmp/coffee-shop-zoomed.png"
convert "$RECEIPT_IMAGE" -fuzz 3% -trim +repage -bordercolor white -border 5% "$ZOOMED_IMAGE"
echo "  original: $(identify -format '%wx%h' "$RECEIPT_IMAGE")"
echo "  zoomed:   $(identify -format '%wx%h' "$ZOOMED_IMAGE")"

echo "=== Pushing receipt image to emulator ==="
APP_FILES="/data/data/com.liveverify.app/files"
$ADB push "$ZOOMED_IMAGE" /data/local/tmp/coffee-shop-receipt.png
$ADB shell run-as com.liveverify.app mkdir -p "$APP_FILES"
$ADB shell run-as com.liveverify.app cp /data/local/tmp/coffee-shop-receipt.png "$APP_FILES/"
IMAGE_PATH="${APP_FILES}/coffee-shop-receipt.png"

echo "=== Launching verification (image OCR mode) ==="
# 10.0.2.2 is the Android emulator's alias for the host machine's loopback.
DNS_OVERRIDES="r.the-daily-grind.co.uk=10.0.2.2,hmrc.gov.uk=10.0.2.2,gov.uk=10.0.2.2"

# Dismiss ANR dialogs (swiftshader GPU triggers "System UI isn't responding").
# Taps "Wait" button whenever it appears.
dismiss_anr_once() {
    $ADB shell uiautomator dump /sdcard/ui.xml 2>/dev/null || true
    $ADB pull /sdcard/ui.xml /tmp/anr-ui.xml 2>/dev/null || true
    if grep -q 'text="Wait"' /tmp/anr-ui.xml 2>/dev/null; then
        local bounds=$(grep -oP 'text="Wait"[^>]*bounds="\K[^"]+' /tmp/anr-ui.xml | head -1)
        if [ -n "$bounds" ]; then
            local x1=$(echo "$bounds" | sed 's/\[/\n/g;s/\]/\n/g' | grep ',' | head -1 | cut -d',' -f1)
            local y1=$(echo "$bounds" | sed 's/\[/\n/g;s/\]/\n/g' | grep ',' | head -1 | cut -d',' -f2)
            local x2=$(echo "$bounds" | sed 's/\[/\n/g;s/\]/\n/g' | grep ',' | tail -1 | cut -d',' -f1)
            local y2=$(echo "$bounds" | sed 's/\[/\n/g;s/\]/\n/g' | grep ',' | tail -1 | cut -d',' -f2)
            local cx=$(( (x1 + x2) / 2 ))
            local cy=$(( (y1 + y2) / 2 ))
            $ADB shell input tap "$cx" "$cy" 2>/dev/null || true
            echo "    dismissed ANR dialog"
        fi
    fi
}

# Background ANR dismisser — polls every 3s and taps "Wait" if it appears.
# This keeps ML Kit alive through swiftshader slowness.
# Note: must inline the adb logic because bash functions aren't inherited by subshells.
ANR_DISMISSER_PID=""
start_anr_dismisser() {
    (
        ADB_CMD="$ADB_BIN -s emulator-5554"
        while true; do
            $ADB_CMD shell uiautomator dump /sdcard/ui.xml 2>/dev/null || true
            $ADB_CMD pull /sdcard/ui.xml /tmp/anr-ui.xml 2>/dev/null || true
            if grep -q 'text="Wait"' /tmp/anr-ui.xml 2>/dev/null; then
                bounds=$(grep -oP 'text="Wait"[^>]*bounds="\K[^"]+' /tmp/anr-ui.xml | head -1)
                if [ -n "$bounds" ]; then
                    x1=$(echo "$bounds" | sed 's/\[/\n/g;s/\]/\n/g' | grep ',' | head -1 | cut -d',' -f1)
                    y1=$(echo "$bounds" | sed 's/\[/\n/g;s/\]/\n/g' | grep ',' | head -1 | cut -d',' -f2)
                    x2=$(echo "$bounds" | sed 's/\[/\n/g;s/\]/\n/g' | grep ',' | tail -1 | cut -d',' -f1)
                    y2=$(echo "$bounds" | sed 's/\[/\n/g;s/\]/\n/g' | grep ',' | tail -1 | cut -d',' -f2)
                    cx=$(( (x1 + x2) / 2 ))
                    cy=$(( (y1 + y2) / 2 ))
                    $ADB_CMD shell input tap "$cx" "$cy" 2>/dev/null || true
                    echo "    dismissed ANR dialog"
                fi
            fi
            sleep 3
        done
    ) &
    ANR_DISMISSER_PID=$!
}
stop_anr_dismisser() {
    if [ -n "$ANR_DISMISSER_PID" ] && kill -0 "$ANR_DISMISSER_PID" 2>/dev/null; then
        kill "$ANR_DISMISSER_PID" 2>/dev/null || true
        wait "$ANR_DISMISSER_PID" 2>/dev/null || true
        ANR_DISMISSER_PID=""
    fi
}

# Launch with image path — ML Kit OCR runs on the receipt screenshot,
# exercising the full camera→OCR→normalize→hash→verify pipeline.
$ADB shell am start \
    -n com.liveverify.app/.MainActivity \
    --es com.liveverify.app.VERIFY_IMAGE "$IMAGE_PATH" \
    --es com.liveverify.app.DNS_OVERRIDES "$DNS_OVERRIDES"

# Start background ANR dismisser, then wait for ML Kit + verification.
# swiftshader GPU makes ML Kit very slow and triggers ANR dialogs that
# block the app unless dismissed. The dismisser taps "Wait" every 3s.
echo "Waiting for verification to complete (dismissing ANR dialogs in background)..."
start_anr_dismisser
sleep 90
stop_anr_dismisser

# ── 6. Capture results ───────────────────────────────────────────

echo "=== Dumping logcat (LiveVerify + StitchRows + ExtractCert) ==="
LOGCAT_FILE="${RESULTS_DIR}/android-coffee-logcat.txt"
$ADB logcat -d -s LiveVerify:D StitchRows:D ExtractCert:D > "$LOGCAT_FILE"
echo "  logcat saved to $LOGCAT_FILE ($(wc -l < "$LOGCAT_FILE") lines)"
# Also print key lines to stdout
echo "--- StitchRows ---"
grep "StitchRows" "$LOGCAT_FILE" || echo "  (no StitchRows entries)"
echo "--- ExtractCert ---"
grep "ExtractCert" "$LOGCAT_FILE" || echo "  (no ExtractCert entries)"
echo "--- LiveVerify OCR ---"
grep -E "OCR from image|Found URL|line\[" "$LOGCAT_FILE" | head -40 || echo "  (no OCR entries)"
echo "---"

echo "=== Capturing screenshots ==="
mkdir -p "$RESULTS_DIR"

# Main result
$ADB shell screencap -p /sdcard/android-coffee-result.png
$ADB pull /sdcard/android-coffee-result.png "${RESULTS_DIR}/android-coffee-result.png"
echo "  result screenshot saved"

# Captured tab
dismiss_anr_once
$ADB shell screencap -p /sdcard/android-coffee-captured.png
$ADB pull /sdcard/android-coffee-captured.png "${RESULTS_DIR}/android-coffee-captured.png"
echo "  captured tab saved"

# Use uiautomator to find and tap tabs by text content.
tap_tab() {
    local tab_text="$1"
    $ADB shell uiautomator dump /sdcard/ui.xml 2>/dev/null
    $ADB pull /sdcard/ui.xml /tmp/android-ui.xml 2>/dev/null
    local bounds=$(grep -oP "text=\"${tab_text}\"[^>]*bounds=\"\K[^\"]+" /tmp/android-ui.xml 2>/dev/null | head -1)
    if [ -n "$bounds" ]; then
        local x1=$(echo "$bounds" | sed 's/\[/\n/g' | sed 's/\]/\n/g' | grep ',' | head -1 | cut -d',' -f1)
        local y1=$(echo "$bounds" | sed 's/\[/\n/g' | sed 's/\]/\n/g' | grep ',' | head -1 | cut -d',' -f2)
        local x2=$(echo "$bounds" | sed 's/\[/\n/g' | sed 's/\]/\n/g' | grep ',' | tail -1 | cut -d',' -f1)
        local y2=$(echo "$bounds" | sed 's/\[/\n/g' | sed 's/\]/\n/g' | grep ',' | tail -1 | cut -d',' -f2)
        local cx=$(( (x1 + x2) / 2 ))
        local cy=$(( (y1 + y2) / 2 ))
        $ADB shell input tap "$cx" "$cy"
        echo "    tapped $tab_text at ($cx, $cy)"
    else
        echo "    WARNING: could not find tab '$tab_text' in UI dump"
        grep -o 'text="[^"]*"' /tmp/android-ui.xml 2>/dev/null | head -20 || true
    fi
}

# Tap "Extracted" tab
tap_tab "Extracted"
sleep 2
dismiss_anr_once
$ADB shell screencap -p /sdcard/android-coffee-extracted.png
$ADB pull /sdcard/android-coffee-extracted.png "${RESULTS_DIR}/android-coffee-extracted.png"
echo "  extracted tab saved"

# Tap normalized tabs — on success there's one "Normalized" tab,
# on failure there are "Normalized-1", "Normalized-2", etc.
# Try the single "Normalized" first, then numbered variants.
$ADB shell uiautomator dump /sdcard/ui.xml 2>/dev/null
$ADB pull /sdcard/ui.xml /tmp/android-ui.xml 2>/dev/null
if grep -q 'text="Normalized-1"' /tmp/android-ui.xml 2>/dev/null; then
    # Multiple candidates — screenshot each
    for n in 1 2 3 4 5; do
        if grep -q "text=\"Normalized-${n}\"" /tmp/android-ui.xml 2>/dev/null; then
            tap_tab "Normalized-${n}"
            sleep 2
            dismiss_anr_once
            $ADB shell screencap -p "/sdcard/android-coffee-normalized-${n}.png"
            $ADB pull "/sdcard/android-coffee-normalized-${n}.png" "${RESULTS_DIR}/android-coffee-normalized-${n}.png"
            echo "  normalized-${n} tab saved"
        fi
    done
else
    tap_tab "Normalized"
    sleep 2
    dismiss_anr_once
    $ADB shell screencap -p /sdcard/android-coffee-normalized.png
    $ADB pull /sdcard/android-coffee-normalized.png "${RESULTS_DIR}/android-coffee-normalized.png"
    echo "  normalized tab saved"
fi

# Optional: short video capture
echo "=== Recording demo video (12 seconds) ==="
$ADB shell am force-stop com.liveverify.app
sleep 1
$ADB shell screenrecord --time-limit 12 /sdcard/android-coffee-demo.mp4 &
RECORD_PID=$!
sleep 1
$ADB shell am start \
    -n com.liveverify.app/.MainActivity \
    --es com.liveverify.app.VERIFY_IMAGE "$IMAGE_PATH" \
    --es com.liveverify.app.DNS_OVERRIDES "$DNS_OVERRIDES"
wait $RECORD_PID 2>/dev/null || true
$ADB pull /sdcard/android-coffee-demo.mp4 "${RESULTS_DIR}/android-coffee-demo.mp4" 2>/dev/null || \
    echo "Video pull failed (may not be ready yet)"
echo "Video saved: ${RESULTS_DIR}/android-coffee-demo.mp4"

echo ""
echo "=== Android coffee shop test complete! ==="
echo "Results in: ${RESULTS_DIR}/"
